src/ideas_portal/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from users import views as user_views
from users.views import uclsso
from ideas.views import (index, dashboard, idea_detail, idea_create, idea_update, idea_delete, review, search, vote, idea_submit)
from challenges.views import challenge_delete, challenge_update, challenges, subscribe, ChallengeDetailView, challenge_create
from contact import views as contact_views
from community_guideline import views as community_view

import django_cas_ng.views as cas_views
import allauth.account.views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('ideas/', dashboard, name='idea-list'),
    path('challenges/', challenges, name='challenge-list'),
    path('challenge/<pk>/',ChallengeDetailView.as_view(), name = 'challenge-detail'),
    path('challenge-create/',challenge_create, name = 'challenge-create'),
    path('challenge/<pk>/update/', challenge_update, name='challenge-update'),
    path('challenge/<pk>/delete/', challenge_delete, name='challenge-delete'),
    path('challenge/<pk>/create/',idea_submit, name = 'idea-submit'),
    path('idea/<pk>/', idea_detail, name = 'idea-detail'),
    path('idea/<slug:slug>/review', review, name = 'idea-review'),
    path('create/', idea_create, name = 'idea-create'),
    path('idea/<pk>/update/', idea_update, name='idea-update'),
    path('idea/<pk>/delete/', idea_delete, name='idea-delete'),
    path('profile/', user_views.profile,name='profile'),
    path('user/<str:username>', user_views.UserProfile.as_view(), name='user-profile'),
    path('search/', search, name='search'),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')), #allauth views, including signup, login, logout, reset password
    path('vote/', vote, name='vote'),
    path('subscribe/', subscribe , name='subscribe'),
    path('leaderboard/', user_views.leaderboard, name='leaderboard'),
    path('callback/', uclsso, name='uclsso' ),
    path('contact/', contact_views.contact_us, name='contact-us'),
    path('community_guide/', community_view.GuidelineList.as_view(), name= 'guideline-list'),
    path('community_guide/<pk>/', community_view.GuidelineDetail.as_view(template_name  = 'community_guideline/community_guide_detail.html'), name= 'guideline-detail'),
    path('account/login', cas_views.LoginView.as_view(), name='cas_ng_login'),
    path('account/login', cas_views.LogoutView.as_view(), name='cas_ng_logout'),
    path('accounts/login/', auth_views.LoginView ,name='login'),
    
    #path('', include('loaderio.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/challenges/models.py

from django.utils import timezone
from django.db import models
from django.urls import reverse
from ideas.models import Idea
from tinymce.models import HTMLField
from django.contrib.auth import get_user_model
User = get_user_model()
Q= models.Q
# Create your models here.

class Criteria(models.Model):
    description = models.CharField(max_length=100)
    def __str__(self):
        return self.description

class ChallengeManager(models.Manager):
    def posted(self):
        now = timezone.now()
        return self.get_queryset().filter(published_date__lte=now)
    def draft(self):
        now = timezone.now()
        return self.get_queryset().filter(Q(published_date__gt=now)|Q(published_date__isnull=True))

class Challenge(models.Model):
    class State(models.TextChoices):
        ACTIVE = 'ACTIVE'
        ENDED = 'ENDED'

    author = models.ForeignKey(User, null =True,on_delete=models.SET_NULL)
    title = models.CharField(db_index=True, max_length=255)
    description = HTMLField()
    published_date = models.DateTimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    idea_submission_deadline = models.DateField()
    tags = models.ManyToManyField(
        'ideas.Tag', related_name='tag_challenges', blank=True
    )
    idea_count = models.IntegerField(default =0)
    criterias = models.ManyToManyField(Criteria)
    thumbnail = models.ImageField(default='defaultbg.jpg',blank=True)
    subscribers = models.ManyToManyField(User,related_name = 'subscriptions', default=None,blank=True)
    subscribers_count = models.IntegerField(default =0)
    state = models.CharField(choices = State.choices, default = State.ACTIVE,max_length=6)
    objects = ChallengeManager()
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('challenge-detail', kwargs={
            'pk': self.pk
        })  

    def is_active(self):
        return self.state == self.State.ACTIVE  

    @property
    def get_ideas(self):
        return self.ideas.all().order_by('-date_posted')

    @property
    def idea_count(self):
        return Idea.objects.approved().filter(challenge=self).count()



src/challenges/forms.py
from django import forms
from django.forms.widgets import SelectDateWidget
from tinymce.widgets import TinyMCE
from .models import Challenge
from django.utils.translation import gettext_lazy as _

class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False

class ChallengeForm(forms.ModelForm):
    description = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'cols': 30, 'rows': 10}
        ),
        help_text='Give a short description of your idea'
    )
    idea_submission_deadline = forms.DateField(widget=SelectDateWidget(
        attrs ={'style': 'display: inline-block; width: auto;'}
    ) , label='Idea Submission Deadline') 
    class Meta:
        model = Challenge
        fields = ('title', 'description', 'thumbnail', 'idea_submission_deadline','tags')
        help_texts = {
            'tags': _('Choose which topics your challenge belongs to'),
        }
        widgets ={
            'tags': forms.CheckboxSelectMultiple,
        }
    

src/ideas/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from tinymce.widgets import TinyMCE
from .models import Idea, Comment, CriteriaScore
from django.utils.translation import gettext_lazy as _



class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False

SCORE_CHOICE = [(i,str(i)) for i in range (0,11)]
class CriteriaScoreForm(forms.ModelForm):
    class Meta:
        model = CriteriaScore
        fields = ('score',)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class ='form-horizontal'
        self.helper.label_class = 'col-lg-5'
        self.helper.field_class = 'col-lg-4'
        self.helper.form_tag = False


class IdeaForm(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )
    class Meta:
        model = Idea
        fields = ('title', 'overview', 'content', 'thumbnail', 
        'tags')
        help_texts = {
            'tags': _('Choose which topics your idea belongs to'),
            'overview':_('Give a short description of your idea'),
        }
        widgets ={
            'tags': forms.CheckboxSelectMultiple
        }

class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Type your comment',
        'id': 'usercomment',
        'rows': '4'
    }))
    class Meta:
        model = Comment
        fields = ('content', )

src/challenges/views.py
from django.contrib.auth.decorators import login_required ,permission_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import models
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render,redirect,reverse
from django.db.models import Count, Q
from django.utils import timezone
from ideas_portal.decorators import is_challenge_creator
from users.models import Profile
from .models import Challenge, Criteria
from .forms import ChallengeForm
from django.views.generic import DetailView
# Create your views here.

    
def get_category_count():
    queryset = Challenge .objects .values('tags__title').exclude(tags__title__isnull=True) .annotate(Count('tags__title'))
    return queryset

def is_valid_queryparam(param):
    return param != '' and param is not None and param

def get_criterias():
    return Criteria.objects.all()

def challenges(request):
    category_count = get_category_count()
    challenge_list = Challenge.objects.posted().all().order_by('-published_date')
    categories = request.GET.getlist('category')
    sort = request.GET.get('sort')
    status = request.GET.getlist('status')

    if is_valid_queryparam(sort):
        if sort == "popularity":
            challenge_list= challenge_list.annotate(icount=Count('ideas',filter=models.Q(ideas__approved=True))).order_by('-icount')
        elif sort == "newest":
            challenge_list=challenge_list.order_by('-published_date')
    else:
        sort = "newest"
        
    if is_valid_queryparam(categories):
        challenge_list = challenge_list.filter(tags__title__in=categories).distinct()

    if is_valid_queryparam(status):
        if len(status)==1:
            if status[0] == 'active':
                challenge_list = challenge_list.filter(state=Challenge.State.ACTIVE)
                
            else:
                challenge_list = challenge_list.filter(state=Challenge.State.ENDED)
                
    
    paginator=Paginator(challenge_list,9)
    page_req_var = 'page'
    page = request.GET.get(page_req_var)
    
    try:
        paginated_queryset = paginator.page(page)
    except PageNotAnInteger:
        paginated_queryset = paginator.page(1)
    except EmptyPage:
        #return last page
        paginated_queryset = paginator.page(paginator.num_pages)

    context = {
        'challenges_count' : challenge_list.count(),
        'queryset': paginated_queryset,
        'page_request_var' : page_req_var,
        'category_count' : category_count,
        'categories' : categories,
        'sort' : sort,
        'status' : status
    }
    return render(request,'challenges.html',context)

class ChallengeDetailView(DetailView):
    model = Challenge
    template_name = 'challenge_detail.html'
    context_object_name = 'challenge'
    def get_context_data(self, **kwargs):
        challenge = super().get_object()
        idea_list = challenge.ideas.all().filter(Q(approved=True))
        
        # try:
        if challenge.subscribers.filter(id=self.request.user.id).exists():
            subscribed =True
        else:
            subscribed =False
        # except:
        #     pass
       
        context = super().get_context_data(**kwargs)
        context['page_request_var'] = "page"
        context['subscribed'] = subscribed
        context['idea_list'] = idea_list
        context['next_url'] = reverse("challenge-detail", kwargs={
                'pk': challenge.pk
            })
        return context

img1 = 'gallery-1.jpg'
img2 = 'gallery-2.jpg'
img3 = 'gallery-3.jpg'
img4 = 'gallery-4.jpg'
image_bank = [img1,img2,img3,img4]
@ login_required
@ permission_required('challenges.add_challenge',raise_exception=True)
def challenge_create(request):
    title = 'Create'
    criterias = get_criterias()

    form = ChallengeForm(request.POST or None, request.FILES or None)
    print(form.data)
    if request.method == "POST":
        if form.is_valid():
            form.instance.author = request.user
            image = request.POST.get('image-picker')
            fcriterias = request.POST.getlist('criteria')

            form.save()
            if image:
                form.instance.thumbnail = image
            if 'final' in request.POST:
                form.instance.published_date = timezone.now()
            
            for criteria in fcriterias:
                if Criteria.objects.filter(description=criteria).exists():
                    object= get_object_or_404(Criteria, description=criteria)
                    form.instance.criterias.add(object)
                elif criteria:
                    form.instance.criterias.create(description=criteria)
            form.instance.save()

            return redirect(reverse("challenge-detail", kwargs={
                'pk': form.instance.pk
            }))
            

    context = {
        'title': title,
        'form': form,
        'image_bank' : image_bank,
        'criterias' : criterias
    }
    return render(request, "challenge_create.html", context)

@ login_required
@ is_challenge_creator
def challenge_update(request, pk):
    title = 'Update'
    challenge = get_object_or_404(Challenge, pk = pk)
    form = ChallengeForm(request.POST or None, request.FILES or None, instance=challenge)
    posted = challenge.published_date
    set_criterias = challenge.criterias.all()
    fcriterias = request.POST.getlist('criteria')
    image = request.POST.get('image-picker')

    if request.method == "POST":
        if form.is_valid():
            if image:
                form.instance.thumbnail = image
            if 'final' in request.POST:
                form.instance.published_date = timezone.now()
            form.save()
            for c in set_criterias:
                if c not in fcriterias:
                    form.instance.criterias.remove(c)
                else:
                    fcriterias.remove(c)
            for criteria in fcriterias:
                if Criteria.objects.filter(description=criteria).exists():
                    object= get_object_or_404(Criteria, description=criteria)
                    form.instance.criterias.add(object)
                elif criteria:
                    form.instance.criterias.create(description=criteria)
            form.instance.save()

            return redirect(reverse("challenge-detail", kwargs={
                'pk': form.instance.id
            })) 
    context = {
    'title': title,
    'form': form,
    'posted' : posted,
    'set_criterias' : set_criterias,
    'image_bank' : image_bank,
    }
    return render(request, "challenge_create.html", context)

@ login_required
@ is_challenge_creator
def challenge_delete(request, pk):
    challenge = get_object_or_404(Challenge, pk=pk)
    challenge.delete()
    return redirect(reverse("challenge-list"))


@ login_required
def subscribe(request):
    if request.POST.get('action') == 'post':
        result = ''
        challengeid = request.POST.get('challengeid') 
        id = int(request.POST.get('challengeid'))
        challenge = get_object_or_404(Challenge, id=id)

        if challenge.subscribers.filter(id=request.user.id).exists():
            challenge.subscribers.remove(request.user)
            challenge.subscribers_count -= 1
            subscribed=False
            result = challenge.subscribers_count
            challenge.save()
        else:
            challenge.subscribers.add(request.user)
            challenge.subscribers_count += 1
            subscribed=True
            result = challenge.subscribers_count
            challenge.save()

        return JsonResponse({'result': result,'subscribed' : subscribed, 'challengeid' : challengeid})

src/templates/challenge_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %} 
<style>
    .image_picker_image{
        max-width: 180px;
        max-height: auto;
    }
</style>
<div class="col-8 offset-1 mb-5 mt-5">
    <h3>{{ title }} Challenge</h3>
    {{ form.media }}
    <form method="POST" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field |as_crispy_field }}
            {% if field == form.thumbnail %}
            <div class="form-group">
                <select class="image-picker" name="image-picker">
                    <option value=""></option>
                    {% for img in image_bank %}
                    <option id="{{ img }}" data-img-src="/media/{{ img }}" value="{{ img }}" name="thumbnail"></option>
                    {% endfor %}
                </select>
            </div>
            {% endif %}

        </div>
        {% endfor %}
        <div class="fieldWrapper">
            <div id="div_id_criterias" class="form-group">
                <label for="id_criterias">Criterias</label>
                <button class="add_field_button" style="margin: 5px">Add Criteria</button>
                <div class="input_fields_wrap">
                    {% for criteria in set_criterias %}
                    <div><input type="text" name="criteria" style="margin: 5px;" list="criterias" value="{{ criteria }}"></div>
                    {% endfor %}
                    <div><input type="text" name="criteria" style="margin: 5px;" list="criterias"></div>
                </div>
                <datalist id="criterias">
                    {% for criteria in criterias %}
                    <option value="{{criteria}}">
                    {% endfor %}
                </datalist>
                <small id="hint_id_criterias" class="form-text text-muted">Each idea submitted to this challenge will be evaluated based on the given criterias</small>
            </div>
        </div>
        <!-- {{ form|crispy }} -->
        
        {% if not posted %}
        <button class="btn btn-primary" type="submit" name="draft">Save as draft</button>
        {% endif %}
        <button class="btn btn-primary" type="submit" name="final">Submit</button>

        
        
    </form>

</div>


<script src="{% static 'js/image-picker.min.js' %}"></script>

<script>
    $('.image-picker').imagepicker();
    //custom script to allow user to add criterias to challenge instance
    $(document).ready(function () {
        var max_fields = 10; //maximum input boxes allowed
        var wrapper = $(".input_fields_wrap"); //Fields wrapper
        var add_button = $(".add_field_button"); //Add button ID

        var x = 1; //initlal text box count
        $(add_button).click(function (e) { //on add input button click
            e.preventDefault();
            if (x < max_fields) { //max input box allowed
                x++; //text box increment
                $(wrapper).append('<div><input type="text" name="criteria" style="margin: 5px;" list="criterias"><a href="#" class="remove_field">Remove</a></div>'); //add input box
            }
        });
        $(wrapper).on("click", ".remove_field", function (e) { //user click on remove text
            e.preventDefault(); $(this).parent('div').remove(); x--;
        })
    });
</script>
{% endblock content %}

src/templates/challenge_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/Challenge_detail.css' %}" type="text/css">
<section class="title-section">
  <div class="title-container-1">
    <div class="title-container-2">
      <h1 class="title">{{ challenge.title }}</h1>
      
      {% if request.user.is_authenticated %}
      <div>
        <button class="btn btn-link"id="subscribe-button" value="{{challenge.id}}">
    
          {% if subscribed %}
          <span  style="background-color: grey; color: white;" name="text">UNSUBSCRIBE</span>
          {% else %}
          <span class="btn" style="background-color: green ; color: white;" name="text">SUBSCRIBE</span>
          {% endif %}
        </button>
        <span id="subscriber_count" style="font-size:20px;">{{challenge.subscribers_count}}</span>
      </div>
      {% endif %}
    </div>
    <div style="display: inline;">
      {% for tag in challenge.tags.all %}
      <span class="item-tag">{{ tag }}</span>
      {% endfor %}
    </div>
    
    <div class="details-container">
      <div class="details-container-1">
        <div class="profile-container-1">
          <a href="{% url 'user-profile' challenge.author.username %}">
          <img class="profile-1" src="{{ challenge.author.profile.image.url}}" alt="PICTURE" onerror=this.src="{% static 'logo/user.png' %}">
          </a>
          <a href="{% url 'user-profile' challenge.author.username %}">{{challenge.author}}</a>
        </div> 
        <div class="logo-container-1">
          <img class="logo-1" src="{% static 'logo/deadline.png' %}" aria-label="Deadline">
          <div>{{ challenge.idea_submission_deadline |date:"F d, Y"}}</div>
        </div>  
        <div class="logo-container-1">
          <img class="logo-1" src="{% static 'logo/lightbulb.png' %}" >
          <div>{{ challenge.idea_count }}</div>
        </div>  
  
    </div>
      <div class="details-container-1">

        {% if request.user == challenge.author %}
          <div class="float-right">
            <a class="logo-container-1"  data-toggle="modal" data-target="#deleteModal" style="cursor: pointer;"><img class="logo-1" src="{% static 'logo/delete.png' %}" ></a>
          </div> 
          <!-- Modal -->
          <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
          <div class="modal-dialog" role="document">
          <div class="modal-content">
          <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Confirmation</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          </div>
          <div class="modal-body">  
            Are you sure you want to delete your challenge? 
          </div>
          <div class="modal-footer">
            <a href="{% url 'challenge-delete' pk=challenge.pk %}" class="btn btn-danger">delete</a>
          </div>
          </div>
          </div>
          </div>
          <div class="float-right">
            <a class="logo-container-1" href="{% url 'challenge-update' challenge.id %}"><img class="logo-1" src="{% static 'logo/edit.png' %}" ></a>
          </div>
       
        {% endif %}
  
 
        
       
  
      </div>
    </div>
    <img src="{{ challenge.thumbnail.url }}" class="thumbnail">
  </div>     

</section>
<section class="content-section">
    <div class="content-container">
      {{ challenge.description | safe }}
    </div>
</section>

  <section class="criteria-section">
    <div class="content-container">
      <div class="criteria-title">Judging Criteria</div>
      {% for criteria in challenge.criterias.all %}
      <div class="criteria-1">
        <div>
          {{ criteria.description }}
        </div>
      </div>
      {% endfor %}
       
      {% if challenge.is_active %}
      <div class="btn-container-1">
        {% if not user.is_authenticated %}
        <a class="btn btn-outline-secondary" href="{% url 'account_login' %}?next={{ next_url }}"> Submit Your Idea</a>
        {% else %}
        <a class="btn btn-outline-secondary" href="{% url 'idea-submit' challenge.id %}"> Submit Your Idea </a>
        {% endif %}
      </div>
      {% else %}
      <h5 style="margin: 1rem; ">Challenge has ended. Please check out the submitted ideas below.</h5>
      {% endif %}
    </div>
  </section>

  <section class="ideas-section">
    <div class="idea-container">
      <div class="title-container">  
        <h2 class="submitted-ideas-title">Submitted Ideas</h2>
      </div>
      <div class="ideas">
        {% for idea in idea_list %}
        
        <div class="item-1">
          <div>
            <a href="{{ idea.get_absolute_url }}">
              <img class="idea-img-1" src="{{ idea.thumbnail.url }}" alt="MyPhoto">
            </a>
            <div>
              {% for tag in idea.tags.all %}
              <span class="item-tag">{{ tag }}</span>
              {% empty %}
              <div class="item-tag-1">no tags</div>
              {% endfor %}
            </div>
            <a class="item-title-1" href="{{ idea.get_absolute_url }}">{{idea.title}}</a>
            <div class="p-1">{{ idea.overview }}</div>
  
          
          </div>
          
          <div class="info-container-1">
              <div class="logo-container-1">
                <div>{{ idea.author }}</div>
              </div>
              <div class="logo-container-1">
                  <img class="logo-1" src="{% static 'logo/like.png' %}" >
                  <div>{{ idea.vote_count }}</div>
              </div>
              <div class="logo-container-1">
                <img class="logo-1" src="{% static 'logo/comment.png' %}" >
                <div>{{ idea.comment_count }}</div>
              </div>
          </div>
          </div>
          
          {% empty %}
          <div>No submitted ideas so far. </div>
        {% endfor%}
      </div>

      <div>
           
        <ul class="pagination-list">
            {% if queryset.has_previous %} 
            <li class="page-arrow-container"><a href="#"><img src="{% static 'logo/arrow_left.png'%}" class="page-arrow"></a></li>
            {% endif %}
            <li class="page-item"><a class="text-style" href="#">1</a></li>
            {% if queryset.has_next %}
            <li class="page-arrow-container"><a href="#"><img src="{% static 'logo/arrow_right.png'%}" class="page-arrow"></a></li>
            {% endif %}
        </ul>

    </div>
  </section>
  <script>
    $(document).on('click', '#subscribe-button', function (e) {
      e.preventDefault();
      $.ajax({
        type: 'POST',
        url: "{% url 'subscribe' %}",
        data: {
          challengeid: $('#subscribe-button').val(),
          "csrfmiddlewaretoken": "{{ csrf_token }}",
          action: 'post'
        },
        success: function (json) {
          document.getElementById("subscriber_count").innerHTML = json['result']
          sub = document.getElementsByName("text");
          if (json['subscribed'] == true) {
            $(sub).css("color", "white");
            $(sub).css("background-color", "grey");
            $(sub).text("UNSUBSCRIBE");
          }
          else if (json['subscribed'] == false) {
            $(sub).css("color", "white");
            $(sub).css("background-color", "green");
            $(sub).text("SUBSCRIBE") ;
          }
        },
        error: function (xhr, errmsg, err) {
        }
      });
    })
  </script>
{% endblock content %}



src/templates/contact_us.html
{% extends 'base.html' %}
{%load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/Contact_us.css' %}">


<div class="cover">
    <div class="cover-container">
        <div class="container">
            <h1>How can we help? </h1>
            <p>Use the form below to send us your enquiry. Our customer support team will get back to you as soon as possible. </p>
            <form method="POST" class="post-form">
                {% csrf_token %}
                {{form.as_p}}
                <div class="btn-container">
                    <button type="submit" class="save btn btn-outline-secondary">Submit Enquiry</button>
                </div>
            </form> 
        </div>
        <div class="container-1">
            <div class="info-container">
                <h5>Corporate Office</h5>
                <div>University College London, Gower Street, London WC1E 6BT.</div>
            </div>
            <div class="info-container">
                <h5>Direct Contact</h5>
                <div>Phone: 12345678</div>
                <div>email: ucl@ucl.ac.uk</div>
            </div>
            <div class="info-container">
                <h5>Departments</h5>
                <div>social_science@ucl.ac.uk</div>
                <div>history@ucl.ac.uk</div>
                <div>law@ucl.ac.uk</div>
                <div>engineering@ucl.ac.uk</div>
            </div>
        </div>
    </div>


</div>



{% endblock content%}

src/templates/footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/Footer.css' %}">

<section class="section">
    <div class="footer">
        <h5><b>Idea4U</b></h5>
        <!-- <ul class="logo-list">
            <li><a ><img  class = "logo" src ="{% static 'logo/facebook.png' %}" alt = "mylogo"></a></li>
            <li><a ><img class = "logo" src ="{% static 'logo/instagram.png' %}" alt = "mylogo"></a></li>
            <li><a ><img class = "logo" src ="{% static 'logo/linkedin.png' %}" alt = "mylogo"></a></li>
        </ul> -->
        <!-- <a href ="/contact" class="link">Contact Us</a> -->
        <a href ="/community_guide" class="link"> Community Guidelines</a>
    </div>
</section>

src/templates/header.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/Header.css' %}">


  <nav class="navbar navbar-expand-lg navbar-light ">
    <div class="nav container-fluid">
      <div>
        <a href="/" class="nav-brand"><img class="company-logo" src="{% static 'logo/ucl.png' %}" alt="My Logo"></a>
      </div>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
        <ul class="link-list">
          <li class="link"><a href="/">Home</a></li>
          <li class="link"><a href="/ideas">Ideas</a></li>
          <li class="link"><a href="/challenges">Challenges</a></li>
          <li class="link"><a href="/leaderboard">LeaderBoard</a></li>
          {% if user.is_authenticated %}
          <li class="link"><a href="{% url 'user-profile' user.username  %}">Profile</a>
          </li>
          <li class="link"><a href="/accounts/logout">Log Out </a></li>
          {% else %}
          <li class="link"><a href="/accounts/login">Log In </a></li>
          <li class="link"><a href="/accounts/signup">Sign Up </a></li>
          {% endif %}
          <!-- <li class="link"><a href="/contact">Contact</a></li> -->
  
        </ul>
  
      </div>
    </div>
  </nav>


      {% if messages %}
        {% for message in messages %}
        <div class="row justify-content-center">
          <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        </div>
        {% endfor %}
      {% endif %}
