src/ideas_portal/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from users import views as user_views
from users.views import uclsso
from ideas.views import (index, dashboard, idea_detail, idea_create, idea_update, idea_delete, review, search, vote, idea_submit)
from challenges.views import challenge_delete, challenge_update, challenges, subscribe, ChallengeDetailView, challenge_create
from contact import views as contact_views
from community_guideline import views as community_view

import django_cas_ng.views as cas_views
import allauth.account.views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('ideas/', dashboard, name='idea-list'),
    path('challenges/', challenges, name='challenge-list'),
    path('challenge/<pk>/',ChallengeDetailView.as_view(), name = 'challenge-detail'),
    path('challenge-create/',challenge_create, name = 'challenge-create'),
    path('challenge/<pk>/update/', challenge_update, name='challenge-update'),
    path('challenge/<pk>/delete/', challenge_delete, name='challenge-delete'),
    path('challenge/<pk>/create/',idea_submit, name = 'idea-submit'),
    path('idea/<pk>/', idea_detail, name = 'idea-detail'),
    path('idea/<slug:slug>/review', review, name = 'idea-review'),
    path('create/', idea_create, name = 'idea-create'),
    path('idea/<pk>/update/', idea_update, name='idea-update'),
    path('idea/<pk>/delete/', idea_delete, name='idea-delete'),
    path('profile/', user_views.profile,name='profile'),
    path('user/<str:username>', user_views.UserProfile.as_view(), name='user-profile'),
    path('search/', search, name='search'),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')), #allauth views, including signup, login, logout, reset password
    path('vote/', vote, name='vote'),
    path('subscribe/', subscribe , name='subscribe'),
    path('leaderboard/', user_views.leaderboard, name='leaderboard'),
    path('callback/', uclsso, name='uclsso' ),
    path('contact/', contact_views.contact_us, name='contact-us'),
    path('community_guide/', community_view.GuidelineList.as_view(), name= 'guideline-list'),
    path('community_guide/<pk>/', community_view.GuidelineDetail.as_view(template_name  = 'community_guideline/community_guide_detail.html'), name= 'guideline-detail'),
    path('account/login', cas_views.LoginView.as_view(), name='cas_ng_login'),
    path('account/login', cas_views.LogoutView.as_view(), name='cas_ng_logout'),
    path('accounts/login/', auth_views.LoginView ,name='login'),
    
    #path('', include('loaderio.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/challenges/models.py

from django.utils import timezone
from django.db import models
from django.urls import reverse
from ideas.models import Idea
from tinymce.models import HTMLField
from django.contrib.auth import get_user_model
User = get_user_model()
Q= models.Q
# Create your models here.

class Criteria(models.Model):
    description = models.CharField(max_length=100)
    def __str__(self):
        return self.description

class ChallengeManager(models.Manager):
    def posted(self):
        now = timezone.now()
        return self.get_queryset().filter(published_date__lte=now)
    def draft(self):
        now = timezone.now()
        return self.get_queryset().filter(Q(published_date__gt=now)|Q(published_date__isnull=True))

class Challenge(models.Model):
    class State(models.TextChoices):
        ACTIVE = 'ACTIVE'
        ENDED = 'ENDED'

    author = models.ForeignKey(User, null =True,on_delete=models.SET_NULL)
    title = models.CharField(db_index=True, max_length=255)
    description = HTMLField()
    published_date = models.DateTimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    idea_submission_deadline = models.DateField()
    tags = models.ManyToManyField(
        'ideas.Tag', related_name='tag_challenges', blank=True
    )
    idea_count = models.IntegerField(default =0)
    criterias = models.ManyToManyField(Criteria)
    thumbnail = models.ImageField(default='defaultbg.jpg',blank=True)
    subscribers = models.ManyToManyField(User,related_name = 'subscriptions', default=None,blank=True)
    subscribers_count = models.IntegerField(default =0)
    state = models.CharField(choices = State.choices, default = State.ACTIVE,max_length=6)
    objects = ChallengeManager()
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('challenge-detail', kwargs={
            'pk': self.pk
        })  

    def is_active(self):
        return self.state == self.State.ACTIVE  

    @property
    def get_ideas(self):
        return self.ideas.all().order_by('-date_posted')

    @property
    def idea_count(self):
        return Idea.objects.approved().filter(challenge=self).count()



src/users/models.py
from django.db import models
from django.contrib.auth import get_user_model
from PIL import Image
from django.core.validators import MinValueValidator
# Create your models here.
User = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    occupation = models.CharField(max_length=255, blank=True)
    location =models.CharField(max_length=255, blank=True)
    image = models.ImageField(default= 'default.jpg', upload_to='profile_pics')
    bio = models.CharField(max_length=255, blank=True)
    score = models.IntegerField(default=0, validators=[MinValueValidator(0)])

    def __str__(self):
        return self.user.username


    #overwrite save method to scale images 
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        #resize
        img = Image.open(self.image.path)
        if img.height >300 or img.width >300:
            output_size =(300,300)
            img.thumbnail(output_size)
            img.save(self.image.path) #overwrite

    @property
    def get_subscriptions(self):
        return self.user.subscriptions.all()

    @property
    def get_challenges(self):
        return self.user.challenge_set.all()

    @property
    def get_challenges_draft(self):
        return self.user.challenge_set.draft()

src/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields =['username','email','password1','password2']

    def signup(self, request, user):
        user.username = self.cleaned_data.get('username')
        user.email = self.cleaned_data.get('email')
        user.password = self.cleaned_data.get('password')
        user.save()

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields =['username','email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields =['bio','occupation','location','image']

#when we put this 2 forms on template make it look like one form

src/users/views.py
from django.contrib.auth.models import User
from django.dispatch import receiver
from allauth.account.signals import user_signed_up
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from challenges.models import Challenge
from ideas.models import Idea

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth import login

from django.core.mail import EmailMessage
from django.urls import reverse
from users.models import Profile
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string

from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.middleware import MiddlewareMixin

from django.core.mail import EmailMessage
from django.urls import reverse

from django.views.generic import ListView
import ideas

from ideas_portal.settings import leaderBoard, ucl_client_secret
from django_redis import get_redis_connection

from django.http import HttpResponseRedirect, HttpResponseForbidden

import requests
from django.contrib import auth




def leaderboard(request):    
    scoreboard = redisRank('scoreboard')
    # # rewrite redis database, but would let user logout
    # scoreboard.tearDown()
    # scoreboard.addAll()
    length = scoreboard.get_rank_len()
    rank = scoreboard.get_rank(1, 9)
    user_name = request.user.username
    user_rank = scoreboard.get_user_rank(user_name)
    user_score = scoreboard.get_score(user_name)
    if user_rank < 10:
        user_is_not_top = False
    else:
        user_is_not_top = True

    context ={
        'length' : length,
        'toplist': rank,
        'user_rank' : user_rank,
        'user_score' : user_score,
        'user_name' : user_name,
        'user_is_not_top' : user_is_not_top
    }
    
    return render(request,'leaderboard.html',context)


class redisRank:
    def __init__(self, name):
        self.name = name

    def get_rank(self, start, end):
        # get rank from start to end with user and score
        return leaderBoard.zrevrange(self.name, start-1, end-1, withscores=1)

    def set_score(self, user, score) -> None:
        # add or update user score
        mapping = {user: score}
        leaderBoard.zadd(self.name, mapping)

    # def set_many_score(self, mapping: dict):
    #     # add or update many user score
    #     leaderBoard.zadd(self.name, mapping)

    def get_score(self, user) -> int:
        # get user score
        user_score = leaderBoard.zscore(self.name, user)
        if user_score is None:
            return -1
        else:
            return user_score

    def get_user_rank(self, user) -> int:
        # get user rank (inverted order)
        user_rank = leaderBoard.zrevrank(self.name, user)
        if user_rank is None:
            return -1
        else:
            # zervrank starts at 0
            return user_rank + 1

    def get_rank_len(self):
        # get num of elements in leaderboard
        return leaderBoard.zcard(self.name)

    def tearDown(self):
        # clean all data in redis
        # can run addAll() to recover all data
        get_redis_connection("default").flushall()

    def addAll(self):
        # add all data in redis
        user_list = User.objects.all()
        for user in user_list:
            score = user.profile.score
            user = user.username
            mapping = {user: score}
            leaderBoard.zadd(self.name, mapping)

    def deleteAll(self):
        user_list = User.objects.all()
        for user in user_list:
            leaderBoard.zrem(self.name, user.username)

    def deleteUser(self, instance):
        username=instance.username
        leaderBoard.zrem( self.name , username)
            

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            #to return a success message feedback
            messages.success(request, f"Your account has been updated!")
            return HttpResponseRedirect('/profile')
            #after this update html to show the message
        
    else:
        #arg to link form to database n to display prev data in form
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form' : u_form,
        'p_form' : p_form
    }
    return render(request,'users/profile.html', context)

class UserProfile(ListView):
    model: Idea
    template_name='users/user_profile.html'
    context_object_name='ideas'
    paginate_by = 3

    def get_queryset(self):
        user_obj= get_object_or_404(User, username=self.kwargs.get('username'))
        return Idea.objects.approved().filter(author =user_obj.profile).order_by('-date_posted')
        
    def get_context_data(self, **kwargs):
        user_obj= get_object_or_404(User, username=self.kwargs.get('username'))
        drafts = Idea.objects.draft().filter(author =user_obj.profile)
        challenge_drafts = Challenge.objects.draft().filter(author = user_obj)
        unapproved = Idea.objects.unapproved().filter(challenge__author = user_obj)

        context = super().get_context_data(**kwargs)
        context['user_obj'] = user_obj.profile
        context['drafts'] = drafts
        context['challenge_drafts'] = challenge_drafts
        context['unapproved'] = unapproved

        return context
   
def uclsso(request):

    info = receive_callback(request)
    
    try:
        #department = info.get("department")
        email = info.get("email")
        full_name = info.get("full_name")
        #cn = info.get("cn") #UCL username
        #given_name = info.get("given_name")
        #upi = info.get("upi")
        is_student = info.get("is_student")
    except:
        print("info error!")
        return HttpResponseRedirect('/accounts/login')
    

    if full_name == None or email == None: #if full_name is null, just goes back to login page
        print("sso fail, full_name is null")
        return HttpResponseRedirect('/accounts/login')

    full_name = full_name.replace(" ","")

    # get user object if created
    try:
        user = User.objects.get(username=full_name)    
    except User.DoesNotExist: #create new user if not exist
        user = User(username=full_name)
        user.email = email
        user.email_confirmed = True
        user.is_staff = False
        user.is_active = True
        user.is_valid = True
        user.save()

    #login user  
    try:
        AutomaticUserLoginMiddleware.process_view(user, request)
    except:
        print("sso login error")
        return HttpResponseRedirect('/accounts/login')

    return HttpResponseRedirect('/')

class AutomaticUserLoginMiddleware(MiddlewareMixin):

    def process_view(user, request, backend='allauth.account.auth_backends.AuthenticationBackend'):
        if not AutomaticUserLoginMiddleware._is_user_authenticated(user):
            user = auth.authenticate(user)
            if user is None:
                return HttpResponseForbidden()

        request.user = user
        auth.login(request, user, backend)
        messages.success(request, f"Login successfully!")

    @staticmethod
    def _is_user_authenticated(user):
        return user.is_authenticated


def receive_callback(request):
    client_secret = ucl_client_secret

    try:
        result = request.GET.get('result')
        code = request.GET.get('code')
        state = request.GET.get('state')
    except:
        print("get request error!")
        return HttpResponseRedirect('/accounts/login')

    params1 = {
        "client_id": "0761046984609257.7533240572162003",
        "code": code,
        "client_secret": client_secret,
    }
    r1 = requests.get("https://uclapi.com/oauth/token", params=params1)
    data = r1.json()
    print(data)
    token = data.get("token")

    params2 = {
        "token": token,
        "client_secret": client_secret,
    }
    r2 = requests.get("https://uclapi.com/oauth/user/data", params=params2)
    info = r2.json()
    print(info)

    return info

src/users/templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %} 
<style>
  .img-radius {
    width: 100%
  }
</style>
<div class=container>
  <div class="row justify-content-left">
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" style="object-fit: cover; width: 7rem; height:7rem; margin:1rem;" src="{{ user.profile.image.url }}">
      </div>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Profile Info</legend>
          {{ u_form|crispy }}
          {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
      </form>
    </div>

  </div>
</div>




{% endblock content %}

src/users/templates/users/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<link rel="stylesheet" href="{% static 'css/UserProfile.css' %}">
<section class="title-section">
  <div class="title-container">
    <div class="img-container">
      <img class="profile-custom"src="{{ user_obj.image.url }}"> 
      <div>
        {% if user_obj == user.profile %}
        <a href="{% url 'profile' %}" class="edit-btn btn btn-outline-secondary profile-btn"><span>edit profile</span></a>
        {% endif %}
      </div>
    </div>
    <div class="details-container">
      <h1>{{user_obj}}   </h1>
      <div>
        <span class="occupation">{{user_obj.occupation}}</span>
        <span class="email">{{user_obj.user.email}}</span>
        <span>Score: {{ user.profile.score }}</span>
      </div>
      
      <div></div>
      <div>{{user_obj.bio}}
      </div>
    </div>
  </div>
  
</section>

<section>
  <div class="tab-container">
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-ideas" role="tab"
          aria-controls="nav-ideas" aria-selected="true">Ideas</a>
        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-subscriptions" role="tab"
          aria-controls="nav-subscriptions" aria-selected="false">Subscribed</a>
        {% if user_obj == user.profile %}
        <a class="nav-item nav-link" id="nav-home-tab" data-toggle="tab" href="#nav-notifications" role="tab"
          aria-controls="nav-notifications" aria-selected="false">Notifications</a>
        <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-drafts" role="tab"
          aria-controls="nav-drafts" aria-selected="false">Idea Drafts</a>
        {% if perms.challenges.add_challenge %}
        <a class="nav-item nav-link" id="nav-challenges-tab" data-toggle="tab" href="#nav-challenges" role="tab"
          aria-controls="nav-challenges" aria-selected="false">Challenges</a>
        <a class="nav-item nav-link" id="nav-challenge_drafts-tab" data-toggle="tab" href="#nav-challenge_drafts" role="tab"
          aria-controls="nav-challenge_drafts" aria-selected="false">Challenge Drafts</a>
        <a class="nav-item nav-link" id="nav-pending-tab" data-toggle="tab" href="#nav-pending" role="tab"
          aria-controls="nav-pending" aria-selected="false">Approve List</a>
        {% endif %}
        {% endif %}
      </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-ideas" role="tabpanel" aria-labelledby="nav-ideas-tab">
        <header>
          {% if user_obj == user.profile %}
          <p>
          <h3 class="mb-3">My Ideas ({{ page_obj.paginator.count }}) </h3>
          </p>
          {% else %}
          <p>
          <h3 class="mb-3">Ideas by {{ view.kwargs.username }} ({{ page_obj.paginator.count }}) </h3>
          </p>
          {% endif %}
        </header>
        <div class="row">
          {% for idea in ideas %}
          <div class="item-1">
            <div>
              <a href="{{ idea.get_absolute_url }}">
                <img class="idea-img-1" src="{{ idea.thumbnail.url }}" alt="MyPhoto">
              </a>
              <div>
                {% for tag in idea.tags.all %}
                <span class="item-tag">{{ tag }}</span>
                {% empty %}
                <div class="item-tag-1">no tags</div>
                {% endfor %}
              </div>

              <a class="item-title-1" {% if not idea.date_posted %} href="{% url 'idea-update' pk=idea.pk %}" {% else %}
                href="{{ idea.get_absolute_url }}" {% endif %}>{{idea.title}}</a>
              {% if not idea.date_posted %}<a href="{% url 'idea-update' pk=idea.pk %}"> Edit Draft</a>{% endif %}
              <div class="p-1">{{ idea.overview }}</div>

            </div>
            <div class="info-container-1">
              <div class="logo-container-1">
                <img class="logo-1" src="{% static 'logo/deadline.png' %}">
                <div>{{ idea.date_posted |date:"F d, Y" }}</div>
              </div>

            </div>


          </div>
          {%empty%}
          <p>No ideas.</p>
          {% endfor %}
          {% if is_paginated %}
          <ul class="pagination-list">
            {% if page_obj.has_previous %}
            <li class="page-arrow-container"><a href="?page={{ page_obj.previous_page_number }}"><img
                  src="{% static 'logo/arrow_left.png'%}" class="page-arrow"></a></li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
            <li class="page-item"><b class="text-style" style="color:antiquewhite; cursor: default;">{{page_obj.number }}</b></li>
            {% endif %}
            {%endfor%}
            {% if page_obj.has_next %}
            <li class="page-arrow-container"><a href="?page={{ page_obj.paginator.num_pages }}"><img
                  src="{% static 'logo/arrow_right.png'%}" class="page-arrow"></a></li>
            {% endif %}
          </ul>
          {% endif %}
        </div>
      </div>

      <div class="tab-pane fade" id="nav-subscriptions" role="tabpanel" aria-labelledby="nav-subscriptions-tab">
        <header>
          <p>
          <h3 class="mb-3">Subscribed</h3>
          </p>
        </header>
        <div class="row">
          {% for challenge in user_obj.get_subscriptions %}
          <div class="cha-item-1">
            <div>
              <a href="{{ challenge.get_absolute_url }}">
                <img class="cha-item-img-1" src="{{ challenge.thumbnail.url }}" alt="MyPhoto">
              </a>
              <div>
                {% for tag in challenge.tags.all %}
                <span class="cha-item-tag-1">{{ tag }}</span>
                {%empty%}
                <div class="cha-item-tag-empty">No tags </div>
                {% endfor %}
              </div>
              <div>
                <a class="cha-item-title-1" href="{{ challenge.get_absolute_url }}">{{challenge.title}}</a>
              </div>
            </div>
        
            <div class="info-container-1">
              <div class="logo-container-1">
                <img class="logo-1" src="{% static 'logo/deadline.png' %}">
                <div>{{ challenge.idea_submission_deadline |date:"F d, Y" }}</div>
              </div>
              <div class="logo-container-1">
                <img class="logo-1" src="{% static 'logo/lightbulb.png' %}">
                <div>{{ challenge.idea_count }}</div>
              </div>
            </div>
          </div>
          {%empty%}
          <p>No Subscribed Challenges.</p>
          {% endfor %}
        </div>
      </div>

      <div class="tab-pane fade" id="nav-notifications" role="tabpanel" aria-labelledby="nav-notifications-tab">
        <header>
          <p>
          <h3 class="mb-3">Notifications</h3>
          </p>
        </header>
        <div class="col-md-10 col-md-offset-1">
          <ul class="noti-list">
            {% for notification in request.user.notifications.all %}
            <li class="noti-item"><b class="noti-actor">{{ notification.actor }}</b> {{ notification.verb }}:
              <br>
              {% if notification.description|length > 0 %}
              "{{ notification.description }}"
              <br>
              {% endif %}
              <font color="grey">{{ notification.timesince }} ago</font>
            </li>

            {% empty %}
            No notifications.
            {% endfor %}
          </ul>

        </div>
      </div>

      <div class="tab-pane fade" id="nav-drafts" role="tabpanel" aria-labelledby="nav-drafts-tab">
        <header>
          <p>
          <h3 class="mb-3">Idea Drafts</h3>
          </p>
        </header>
        <div class="row">
          {% for draft in drafts %}
          <div class="item-1">
            <div>
              <a href="{{ draft.get_absolute_url }}">
                <img class="idea-img-1" src="{{ draft.thumbnail.url }}" alt="MyPhoto">
              </a>
              <div>Last modified: {{ draft.date_modified |date:"F d, Y" }}</div>
              <a class="item-title-1" href="{% url 'idea-update' pk=draft.pk %}">{{ draft.title }}</a>
              <div>
                <a href="{% url 'idea-update' pk=draft.pk %}"> Edit Draft</a>
              </div>
              <div class="p-1">{{ draft.overview }}</div>
        
            </div>
          </div>
        
        
        
          {%empty%}
          <p>No Drafts.</p>
          {% endfor %}
        </div>
      </div>
      <div class="tab-pane fade" id="nav-challenges" role="tabpanel" aria-labelledby="nav-challenges-tab">
        <header>
          <p>
          <h3 class="mb-3">Challenges Posted</h3>
          </p>
        </header>
        <div class="row">
          {% for challenge in user_obj.get_challenges %}
          <div class="cha-item-1">
            <div>
              <a href="{{ challenge.get_absolute_url }}">
                <img class="cha-item-img-1" src="{{ challenge.thumbnail.url }}" alt="MyPhoto">
              </a>
              <div>
                {% for tag in challenge.tags.all %}
                <span class="cha-item-tag-1">{{ tag }}</span>
                {%empty%}
                <div class="cha-item-tag-empty">No tags </div>
                {% endfor %}
              </div>
              <div>
                <a class="cha-item-title-1" href="{{ challenge.get_absolute_url }}">{{challenge.title}}</a>
              </div>
            </div>

            <div class="info-container-1">
              <div class="logo-container-1">
                <img class="logo-1" src="{% static 'logo/deadline.png' %}">
                <div>{{ challenge.idea_submission_deadline |date:"F d, Y" }}</div>
              </div>
              <div class="logo-container-1">
                <img class="logo-1" src="{% static 'logo/lightbulb.png' %}">
                <div>{{ challenge.idea_count }}</div>
              </div>
            </div>
          </div>

          {%empty%}
          <p>No Challenges Posted.</p>
          {% endfor %}
        </div>
      </div>
      <div class="tab-pane fade" id="nav-challenge_drafts" role="tabpanel" aria-labelledby="nav-challenge_drafts-tab">
        <header>
          <p>
          <h3 class="mb-3">Challenge Drafts</h3>
          </p>
        </header>
        <div class="row">
          {% for challenge in user_obj.get_challenges_draft %}
          <div class="cha-item-1">
            <div>
              <a href="{{ challenge.get_absolute_url }}">
                <img class="cha-item-img-1" src="{{ challenge.thumbnail.url }}" alt="MyPhoto">
              </a>
              <div>Last modified: {{ challenge.date_modified |date:"F d, Y" }}</div>
              <div>
                <a class="cha-item-title-1" href="{{ challenge.get_absolute_url }}">{{challenge.title}}</a>
              </div>
              <div>
                <a href="{% url 'challenge-update' pk=challenge.pk %}"> Edit Draft</a>
              </div>
            </div>
            {%empty%}
            <p>No Drafts.</p>
            {% endfor %}
          </div>
        </div>
      <div class="tab-pane fade" id="nav-pending" role="tabpanel" aria-labelledby="nav-pending-tab">
        <header>
          <p>
          <h3 class="mb-3">Pending Ideas</h3>
          </p>
        </header>
        <div class="row">
          {% for pending in unapproved %}
            <div class="item-1">
              <div>
                <a href="{{ pending.get_absolute_url }}">
                  <img class="idea-img-1" src="{{ pending.thumbnail.url }}" alt="MyPhoto">
                </a>
                <a class="item-title-1" href="{{ pending.get_absolute_url }}">{{ pending.title }}</a>
                <div class="p-1">{{ pending.overview }}</div>
              </div>
            </div>
          {%empty%}
            <p>No Unapproved Ideas.</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}